### PR TITLE
Log manager interface extension

### LINKED ISSUE #12: LogManager: Support format strings for user and debug exceptions
Instead of using a simple string message in logDebugException/logUserException,
a formatstring with Object... args would be quite convenient.
This could easily be archived by overloading the method.

There could also be a benefit in perforamance if these string only get built if acutally logged. (see logf)

### PR DESCRIPTION
**Pull request by BCSol**
Implementation proposal to resolve #12.

Introduced `log( ... , Object... args)` and `logf(... , String format, Object... args)` for:
- `logUserException`
- `logDebugException`
- `logException`

Removed `logException(Throwable e)` since it's kind of the same as calling `logException(Throwable e,  Object... args)` with no additional arguments.

Dropped `@Nullable String` parameter altogether.
For old `log(.... , null)` calls, it will cause a compiler warning

### CODE REVIEW

File: src/org/sosy_lab/common/log/TestLogManager.java [hunk 1]
```diff
@@ -83,25 +82,46 @@ public void logf(Level pPriority, String pFormat, Object... pArgs) {
   }
 
   @Override
-  public void logUserException(Level pPriority, Throwable pE, @Nullable String pAdditionalMessage) {
+  public void logUserException(Level pPriority, Throwable pE, Object... pArgs) {
     checkNotNull(pPriority);
     checkNotNull(pE);
+    checkNotNull(pArgs);
```
Comment (PhilippWendler) [inline src/org/sosy_lab/common/log/TestLogManager.java]: This and similar methods should get the same checks as `log(Level, Object...)`, probably by refactoring them out into a separate method.

File: src/org/sosy_lab/common/log/TestLogManager.java [hunk 2]
```diff
@@ -83,25 +82,46 @@ public void logf(Level pPriority, String pFormat, Object... pArgs) {
...
   }
 
   @Override
-  public void logDebugException(Throwable pE, @Nullable String pAdditionalMessage) {
+  public void logfUserException(Level pPriority, Throwable pE, String pFormat, Object... pArgs) {
+    checkNotNull(pPriority);
     checkNotNull(pE);
+    checkNotNull(pFormat);
+    checkNotNull(pArgs);
```
Comment (PhilippWendler) [inline src/org/sosy_lab/common/log/TestLogManager.java]: This and similar methods should get the same checks as `logf(Level, String, Object...)`, probably by refactoring them out into a separate method.

File: src/org/sosy_lab/common/log/LogManager.java [hunk 3]
```diff
@@ -94,15 +93,42 @@
...
    * to file FOO.txt (REASON)".
    *
    * @param priority the log level for the message
    * @param e the occurred exception
-   * @param additionalMessage an optional message
+   * @param format The format string.
+   * @param args The arguments for the format string.
    */
-  void logUserException(Level priority, Throwable e, @Nullable String additionalMessage);
+  void logfUserException(Level priority, Throwable e, String format, Object... args);
```
Comment (PhilippWendler) [inline src/org/sosy_lab/common/log/LogManager.java]: Removing the old method breaks binary compatibility. We should therefore only add new methods, and remove none of the old ones.

File: src/org/sosy_lab/common/log/BasicLogManager.java [hunk 4]
```diff
@@ -414,7 +418,95 @@ private void log0(Level priority, StackTraceElement stackElement, String msg) {
...
+      logDebugException(e, args);
+    } else {
+      // but keep calculated results
+      logDebugException(e, additionalMessage);
+    }
+  }
+
+  /** {@inheritDoc} */
+  @Override
+  public void logfUserException(Level priority, Throwable e, String format, Object... args) {
```
Comment (PhilippWendler) [inline src/org/sosy_lab/common/log/BasicLogManager.java]: `logUserException` and `logfUserException` look almost identical, basically only one line changes if I see correctly. Can this be refactored?

File: src/org/sosy_lab/common/log/BasicLogManager.java [hunk 5]
```diff
@@ -414,7 +418,95 @@ private void log0(Level priority, StackTraceElement stackElement, String msg) {
...
+    if (wouldBeLogged(priority)) {
+      additionalMessage = formatString(format, args);
+      StringBuilder logMessage = buildUserExceptionLogMessage(priority, e, additionalMessage);
+      @Var StackTraceElement frame = locateStackTraceElement(e);
+
+      log0(priority, frame, logMessage.toString());
+    }
+    // Enforce lazy string building for DEBUG level
+    if (additionalMessage == null) {
+      logDebugException(e, args);
```
Comment (PhilippWendler) [inline src/org/sosy_lab/common/log/BasicLogManager.java]: Isn't `format` missing here? I am not sure this rather hard-to-understand logic is necessary. Maybe just have `wouldbeLogged(priority) || wouldbeLogged(EXCEPTION_DEBUG_LEVEL)` as condition for building the message?

**Review by PhilippWendler — CHANGES_REQUESTED** [review]

File: src/org/sosy_lab/common/log/BasicLogManager.java (hunk 5 above)
Comment (BCSol) [reply src/org/sosy_lab/common/log/BasicLogManager.java]: Yes I missed the format there.
That is a better solution. 
I will change that

File: src/org/sosy_lab/common/log/BasicLogManager.java (hunk 4 above)
Comment (BCSol) [reply src/org/sosy_lab/common/log/BasicLogManager.java]: I shied away from doing this, cause of the awkard logic structure you mentioned, too.
With the mentioned changes, this will be easier.

File: src/org/sosy_lab/common/log/LogManager.java (hunk 3 above)
Comment (BCSol) [reply src/org/sosy_lab/common/log/LogManager.java]: Would you prefer to extend `logUserException(Level priority, Throwable e, Object... args)` with the missing param.
´logUserException(Level priority, Throwable e, @Nullable String, Object... args)´
Or simply reintroduce the old method?

Comment (PhilippWendler) [reply src/org/sosy_lab/common/log/LogManager.java]: The old method needs to be added exactly as it was, otherwise it is not backwards compatible.

Comment (BCSol) [reply src/org/sosy_lab/common/log/LogManager.java]: Done.

File: src/org/sosy_lab/common/log/TestLogManager.java (hunk 1 above)
Comment (BCSol) [reply src/org/sosy_lab/common/log/TestLogManager.java]: Also Done

File: src/org/sosy_lab/common/log/TestLogManager.java (hunk 2 above)
Comment (BCSol) [reply src/org/sosy_lab/common/log/TestLogManager.java]: Also Done

File: src/org/sosy_lab/common/log/LogManager.java [hunk 6]
```diff
@@ -123,9 +167,32 @@
...
+   *
+   * <p>The message is constructed lazily from <code>String.format(format, args)</code>. To make
+   * individual arguments lazy, use {@link MoreStrings#lazyString(Supplier)}.
+   *
    * @param e the occurred exception
+   * @param format The format string.
+   * @param args The arguments for the format string.
    */
-  void logDebugException(Throwable e);
+  void logfDebugException(Throwable e, String format, Object... args);
```
Comment (PhilippWendler) [inline src/org/sosy_lab/common/log/LogManager.java]: It seems the `logDebugException(Throwable)` override is still missing, right?

File: src/org/sosy_lab/common/log/LoggingOptions.java [hunk 7]
```diff
@@ -92,6 +92,8 @@ public LoggingOptions(Configuration config) throws InvalidConfigurationException
     config.inject(this);
   }
 
+  public LoggingOptions() {}
```
Comment (PhilippWendler) [inline src/org/sosy_lab/common/log/LoggingOptions.java]: This needs to be `protected`, not `public`. Probably should also get a comment that explains that it is for inheritance.

**Review by PhilippWendler — COMMENTED** [review]
Could you please squash all commits that extend `LogManager` into one such that we have a nice history? (But keep the different change to `LoggingOptions` separately.)

File: src/org/sosy_lab/common/log/LogManager.java (hunk 6 above)
Comment (PhilippWendler) [reply src/org/sosy_lab/common/log/LogManager.java]: This is still unsolved.

**Review by PhilippWendler — APPROVED** [review]
